/*
App Store Connect API

Testing GameCenterLeaderboardSetMemberLocalizationsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package appstoreconnect-client

import (
	"context"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"testing"
	openapiclient "github.com/GIT_USER_ID/GIT_REPO_ID"
)

func Test_appstoreconnect-client_GameCenterLeaderboardSetMemberLocalizationsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test GameCenterLeaderboardSetMemberLocalizationsAPIService GameCenterLeaderboardSetMemberLocalizationsCreateInstance", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.GameCenterLeaderboardSetMemberLocalizationsAPI.GameCenterLeaderboardSetMemberLocalizationsCreateInstance(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test GameCenterLeaderboardSetMemberLocalizationsAPIService GameCenterLeaderboardSetMemberLocalizationsDeleteInstance", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		httpRes, err := apiClient.GameCenterLeaderboardSetMemberLocalizationsAPI.GameCenterLeaderboardSetMemberLocalizationsDeleteInstance(context.Background(), id).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test GameCenterLeaderboardSetMemberLocalizationsAPIService GameCenterLeaderboardSetMemberLocalizationsGameCenterLeaderboardGetToOneRelated", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.GameCenterLeaderboardSetMemberLocalizationsAPI.GameCenterLeaderboardSetMemberLocalizationsGameCenterLeaderboardGetToOneRelated(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test GameCenterLeaderboardSetMemberLocalizationsAPIService GameCenterLeaderboardSetMemberLocalizationsGameCenterLeaderboardSetGetToOneRelated", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.GameCenterLeaderboardSetMemberLocalizationsAPI.GameCenterLeaderboardSetMemberLocalizationsGameCenterLeaderboardSetGetToOneRelated(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test GameCenterLeaderboardSetMemberLocalizationsAPIService GameCenterLeaderboardSetMemberLocalizationsGetCollection", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		resp, httpRes, err := apiClient.GameCenterLeaderboardSetMemberLocalizationsAPI.GameCenterLeaderboardSetMemberLocalizationsGetCollection(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test GameCenterLeaderboardSetMemberLocalizationsAPIService GameCenterLeaderboardSetMemberLocalizationsUpdateInstance", func(t *testing.T) {

		t.Skip("skip test")  // remove to run test

		var id string

		resp, httpRes, err := apiClient.GameCenterLeaderboardSetMemberLocalizationsAPI.GameCenterLeaderboardSetMemberLocalizationsUpdateInstance(context.Background(), id).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
