/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect-client

import (
	"encoding/json"
)

// checks if the AppStoreVersionRelationshipsAlternativeDistributionPackage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppStoreVersionRelationshipsAlternativeDistributionPackage{}

// AppStoreVersionRelationshipsAlternativeDistributionPackage struct for AppStoreVersionRelationshipsAlternativeDistributionPackage
type AppStoreVersionRelationshipsAlternativeDistributionPackage struct {
	Links *RelationshipLinks `json:"links,omitempty"`
	Data *AlternativeDistributionPackageVersionRelationshipsAlternativeDistributionPackageData `json:"data,omitempty"`
}

// NewAppStoreVersionRelationshipsAlternativeDistributionPackage instantiates a new AppStoreVersionRelationshipsAlternativeDistributionPackage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppStoreVersionRelationshipsAlternativeDistributionPackage() *AppStoreVersionRelationshipsAlternativeDistributionPackage {
	this := AppStoreVersionRelationshipsAlternativeDistributionPackage{}
	return &this
}

// NewAppStoreVersionRelationshipsAlternativeDistributionPackageWithDefaults instantiates a new AppStoreVersionRelationshipsAlternativeDistributionPackage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppStoreVersionRelationshipsAlternativeDistributionPackageWithDefaults() *AppStoreVersionRelationshipsAlternativeDistributionPackage {
	this := AppStoreVersionRelationshipsAlternativeDistributionPackage{}
	return &this
}

// GetLinks returns the Links field value if set, zero value otherwise.
func (o *AppStoreVersionRelationshipsAlternativeDistributionPackage) GetLinks() RelationshipLinks {
	if o == nil || IsNil(o.Links) {
		var ret RelationshipLinks
		return ret
	}
	return *o.Links
}

// GetLinksOk returns a tuple with the Links field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppStoreVersionRelationshipsAlternativeDistributionPackage) GetLinksOk() (*RelationshipLinks, bool) {
	if o == nil || IsNil(o.Links) {
		return nil, false
	}
	return o.Links, true
}

// HasLinks returns a boolean if a field has been set.
func (o *AppStoreVersionRelationshipsAlternativeDistributionPackage) HasLinks() bool {
	if o != nil && !IsNil(o.Links) {
		return true
	}

	return false
}

// SetLinks gets a reference to the given RelationshipLinks and assigns it to the Links field.
func (o *AppStoreVersionRelationshipsAlternativeDistributionPackage) SetLinks(v RelationshipLinks) {
	o.Links = &v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *AppStoreVersionRelationshipsAlternativeDistributionPackage) GetData() AlternativeDistributionPackageVersionRelationshipsAlternativeDistributionPackageData {
	if o == nil || IsNil(o.Data) {
		var ret AlternativeDistributionPackageVersionRelationshipsAlternativeDistributionPackageData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppStoreVersionRelationshipsAlternativeDistributionPackage) GetDataOk() (*AlternativeDistributionPackageVersionRelationshipsAlternativeDistributionPackageData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *AppStoreVersionRelationshipsAlternativeDistributionPackage) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given AlternativeDistributionPackageVersionRelationshipsAlternativeDistributionPackageData and assigns it to the Data field.
func (o *AppStoreVersionRelationshipsAlternativeDistributionPackage) SetData(v AlternativeDistributionPackageVersionRelationshipsAlternativeDistributionPackageData) {
	o.Data = &v
}

func (o AppStoreVersionRelationshipsAlternativeDistributionPackage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppStoreVersionRelationshipsAlternativeDistributionPackage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Links) {
		toSerialize["links"] = o.Links
	}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableAppStoreVersionRelationshipsAlternativeDistributionPackage struct {
	value *AppStoreVersionRelationshipsAlternativeDistributionPackage
	isSet bool
}

func (v NullableAppStoreVersionRelationshipsAlternativeDistributionPackage) Get() *AppStoreVersionRelationshipsAlternativeDistributionPackage {
	return v.value
}

func (v *NullableAppStoreVersionRelationshipsAlternativeDistributionPackage) Set(val *AppStoreVersionRelationshipsAlternativeDistributionPackage) {
	v.value = val
	v.isSet = true
}

func (v NullableAppStoreVersionRelationshipsAlternativeDistributionPackage) IsSet() bool {
	return v.isSet
}

func (v *NullableAppStoreVersionRelationshipsAlternativeDistributionPackage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppStoreVersionRelationshipsAlternativeDistributionPackage(val *AppStoreVersionRelationshipsAlternativeDistributionPackage) *NullableAppStoreVersionRelationshipsAlternativeDistributionPackage {
	return &NullableAppStoreVersionRelationshipsAlternativeDistributionPackage{value: val, isSet: true}
}

func (v NullableAppStoreVersionRelationshipsAlternativeDistributionPackage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppStoreVersionRelationshipsAlternativeDistributionPackage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


