/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect-client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the TerritoryAvailabilityInlineCreate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &TerritoryAvailabilityInlineCreate{}

// TerritoryAvailabilityInlineCreate struct for TerritoryAvailabilityInlineCreate
type TerritoryAvailabilityInlineCreate struct {
	Type string `json:"type"`
	Id *string `json:"id,omitempty"`
}

type _TerritoryAvailabilityInlineCreate TerritoryAvailabilityInlineCreate

// NewTerritoryAvailabilityInlineCreate instantiates a new TerritoryAvailabilityInlineCreate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewTerritoryAvailabilityInlineCreate(type_ string) *TerritoryAvailabilityInlineCreate {
	this := TerritoryAvailabilityInlineCreate{}
	this.Type = type_
	return &this
}

// NewTerritoryAvailabilityInlineCreateWithDefaults instantiates a new TerritoryAvailabilityInlineCreate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewTerritoryAvailabilityInlineCreateWithDefaults() *TerritoryAvailabilityInlineCreate {
	this := TerritoryAvailabilityInlineCreate{}
	return &this
}

// GetType returns the Type field value
func (o *TerritoryAvailabilityInlineCreate) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *TerritoryAvailabilityInlineCreate) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *TerritoryAvailabilityInlineCreate) SetType(v string) {
	o.Type = v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *TerritoryAvailabilityInlineCreate) GetId() string {
	if o == nil || IsNil(o.Id) {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *TerritoryAvailabilityInlineCreate) GetIdOk() (*string, bool) {
	if o == nil || IsNil(o.Id) {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *TerritoryAvailabilityInlineCreate) HasId() bool {
	if o != nil && !IsNil(o.Id) {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *TerritoryAvailabilityInlineCreate) SetId(v string) {
	o.Id = &v
}

func (o TerritoryAvailabilityInlineCreate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o TerritoryAvailabilityInlineCreate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	if !IsNil(o.Id) {
		toSerialize["id"] = o.Id
	}
	return toSerialize, nil
}

func (o *TerritoryAvailabilityInlineCreate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varTerritoryAvailabilityInlineCreate := _TerritoryAvailabilityInlineCreate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varTerritoryAvailabilityInlineCreate)

	if err != nil {
		return err
	}

	*o = TerritoryAvailabilityInlineCreate(varTerritoryAvailabilityInlineCreate)

	return err
}

type NullableTerritoryAvailabilityInlineCreate struct {
	value *TerritoryAvailabilityInlineCreate
	isSet bool
}

func (v NullableTerritoryAvailabilityInlineCreate) Get() *TerritoryAvailabilityInlineCreate {
	return v.value
}

func (v *NullableTerritoryAvailabilityInlineCreate) Set(val *TerritoryAvailabilityInlineCreate) {
	v.value = val
	v.isSet = true
}

func (v NullableTerritoryAvailabilityInlineCreate) IsSet() bool {
	return v.isSet
}

func (v *NullableTerritoryAvailabilityInlineCreate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTerritoryAvailabilityInlineCreate(val *TerritoryAvailabilityInlineCreate) *NullableTerritoryAvailabilityInlineCreate {
	return &NullableTerritoryAvailabilityInlineCreate{value: val, isSet: true}
}

func (v NullableTerritoryAvailabilityInlineCreate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTerritoryAvailabilityInlineCreate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


