/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnectclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BuildUpdateRequestData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BuildUpdateRequestData{}

// BuildUpdateRequestData struct for BuildUpdateRequestData
type BuildUpdateRequestData struct {
	Type string `json:"type"`
	Id string `json:"id"`
	Attributes *BuildUpdateRequestDataAttributes `json:"attributes,omitempty"`
	Relationships *BuildUpdateRequestDataRelationships `json:"relationships,omitempty"`
}

type _BuildUpdateRequestData BuildUpdateRequestData

// NewBuildUpdateRequestData instantiates a new BuildUpdateRequestData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBuildUpdateRequestData(type_ string, id string) *BuildUpdateRequestData {
	this := BuildUpdateRequestData{}
	this.Type = type_
	this.Id = id
	return &this
}

// NewBuildUpdateRequestDataWithDefaults instantiates a new BuildUpdateRequestData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBuildUpdateRequestDataWithDefaults() *BuildUpdateRequestData {
	this := BuildUpdateRequestData{}
	return &this
}

// GetType returns the Type field value
func (o *BuildUpdateRequestData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *BuildUpdateRequestData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *BuildUpdateRequestData) SetType(v string) {
	o.Type = v
}

// GetId returns the Id field value
func (o *BuildUpdateRequestData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *BuildUpdateRequestData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *BuildUpdateRequestData) SetId(v string) {
	o.Id = v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *BuildUpdateRequestData) GetAttributes() BuildUpdateRequestDataAttributes {
	if o == nil || IsNil(o.Attributes) {
		var ret BuildUpdateRequestDataAttributes
		return ret
	}
	return *o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildUpdateRequestData) GetAttributesOk() (*BuildUpdateRequestDataAttributes, bool) {
	if o == nil || IsNil(o.Attributes) {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *BuildUpdateRequestData) HasAttributes() bool {
	if o != nil && !IsNil(o.Attributes) {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given BuildUpdateRequestDataAttributes and assigns it to the Attributes field.
func (o *BuildUpdateRequestData) SetAttributes(v BuildUpdateRequestDataAttributes) {
	o.Attributes = &v
}

// GetRelationships returns the Relationships field value if set, zero value otherwise.
func (o *BuildUpdateRequestData) GetRelationships() BuildUpdateRequestDataRelationships {
	if o == nil || IsNil(o.Relationships) {
		var ret BuildUpdateRequestDataRelationships
		return ret
	}
	return *o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *BuildUpdateRequestData) GetRelationshipsOk() (*BuildUpdateRequestDataRelationships, bool) {
	if o == nil || IsNil(o.Relationships) {
		return nil, false
	}
	return o.Relationships, true
}

// HasRelationships returns a boolean if a field has been set.
func (o *BuildUpdateRequestData) HasRelationships() bool {
	if o != nil && !IsNil(o.Relationships) {
		return true
	}

	return false
}

// SetRelationships gets a reference to the given BuildUpdateRequestDataRelationships and assigns it to the Relationships field.
func (o *BuildUpdateRequestData) SetRelationships(v BuildUpdateRequestDataRelationships) {
	o.Relationships = &v
}

func (o BuildUpdateRequestData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BuildUpdateRequestData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["id"] = o.Id
	if !IsNil(o.Attributes) {
		toSerialize["attributes"] = o.Attributes
	}
	if !IsNil(o.Relationships) {
		toSerialize["relationships"] = o.Relationships
	}
	return toSerialize, nil
}

func (o *BuildUpdateRequestData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBuildUpdateRequestData := _BuildUpdateRequestData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBuildUpdateRequestData)

	if err != nil {
		return err
	}

	*o = BuildUpdateRequestData(varBuildUpdateRequestData)

	return err
}

type NullableBuildUpdateRequestData struct {
	value *BuildUpdateRequestData
	isSet bool
}

func (v NullableBuildUpdateRequestData) Get() *BuildUpdateRequestData {
	return v.value
}

func (v *NullableBuildUpdateRequestData) Set(val *BuildUpdateRequestData) {
	v.value = val
	v.isSet = true
}

func (v NullableBuildUpdateRequestData) IsSet() bool {
	return v.isSet
}

func (v *NullableBuildUpdateRequestData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBuildUpdateRequestData(val *BuildUpdateRequestData) *NullableBuildUpdateRequestData {
	return &NullableBuildUpdateRequestData{value: val, isSet: true}
}

func (v NullableBuildUpdateRequestData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBuildUpdateRequestData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


