/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect-client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AlternativeDistributionPackageVariantResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AlternativeDistributionPackageVariantResponse{}

// AlternativeDistributionPackageVariantResponse struct for AlternativeDistributionPackageVariantResponse
type AlternativeDistributionPackageVariantResponse struct {
	Data AlternativeDistributionPackageVariant `json:"data"`
	Links DocumentLinks `json:"links"`
}

type _AlternativeDistributionPackageVariantResponse AlternativeDistributionPackageVariantResponse

// NewAlternativeDistributionPackageVariantResponse instantiates a new AlternativeDistributionPackageVariantResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlternativeDistributionPackageVariantResponse(data AlternativeDistributionPackageVariant, links DocumentLinks) *AlternativeDistributionPackageVariantResponse {
	this := AlternativeDistributionPackageVariantResponse{}
	this.Data = data
	this.Links = links
	return &this
}

// NewAlternativeDistributionPackageVariantResponseWithDefaults instantiates a new AlternativeDistributionPackageVariantResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlternativeDistributionPackageVariantResponseWithDefaults() *AlternativeDistributionPackageVariantResponse {
	this := AlternativeDistributionPackageVariantResponse{}
	return &this
}

// GetData returns the Data field value
func (o *AlternativeDistributionPackageVariantResponse) GetData() AlternativeDistributionPackageVariant {
	if o == nil {
		var ret AlternativeDistributionPackageVariant
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *AlternativeDistributionPackageVariantResponse) GetDataOk() (*AlternativeDistributionPackageVariant, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *AlternativeDistributionPackageVariantResponse) SetData(v AlternativeDistributionPackageVariant) {
	o.Data = v
}

// GetLinks returns the Links field value
func (o *AlternativeDistributionPackageVariantResponse) GetLinks() DocumentLinks {
	if o == nil {
		var ret DocumentLinks
		return ret
	}

	return o.Links
}

// GetLinksOk returns a tuple with the Links field value
// and a boolean to check if the value has been set.
func (o *AlternativeDistributionPackageVariantResponse) GetLinksOk() (*DocumentLinks, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Links, true
}

// SetLinks sets field value
func (o *AlternativeDistributionPackageVariantResponse) SetLinks(v DocumentLinks) {
	o.Links = v
}

func (o AlternativeDistributionPackageVariantResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AlternativeDistributionPackageVariantResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	toSerialize["links"] = o.Links
	return toSerialize, nil
}

func (o *AlternativeDistributionPackageVariantResponse) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
		"links",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAlternativeDistributionPackageVariantResponse := _AlternativeDistributionPackageVariantResponse{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAlternativeDistributionPackageVariantResponse)

	if err != nil {
		return err
	}

	*o = AlternativeDistributionPackageVariantResponse(varAlternativeDistributionPackageVariantResponse)

	return err
}

type NullableAlternativeDistributionPackageVariantResponse struct {
	value *AlternativeDistributionPackageVariantResponse
	isSet bool
}

func (v NullableAlternativeDistributionPackageVariantResponse) Get() *AlternativeDistributionPackageVariantResponse {
	return v.value
}

func (v *NullableAlternativeDistributionPackageVariantResponse) Set(val *AlternativeDistributionPackageVariantResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableAlternativeDistributionPackageVariantResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableAlternativeDistributionPackageVariantResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlternativeDistributionPackageVariantResponse(val *AlternativeDistributionPackageVariantResponse) *NullableAlternativeDistributionPackageVariantResponse {
	return &NullableAlternativeDistributionPackageVariantResponse{value: val, isSet: true}
}

func (v NullableAlternativeDistributionPackageVariantResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlternativeDistributionPackageVariantResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


