/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect-client

import (
	"encoding/json"
)

// checks if the AppClipAdvancedExperienceRelationshipsHeaderImage type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppClipAdvancedExperienceRelationshipsHeaderImage{}

// AppClipAdvancedExperienceRelationshipsHeaderImage struct for AppClipAdvancedExperienceRelationshipsHeaderImage
type AppClipAdvancedExperienceRelationshipsHeaderImage struct {
	Data *AppClipAdvancedExperienceRelationshipsHeaderImageData `json:"data,omitempty"`
}

// NewAppClipAdvancedExperienceRelationshipsHeaderImage instantiates a new AppClipAdvancedExperienceRelationshipsHeaderImage object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppClipAdvancedExperienceRelationshipsHeaderImage() *AppClipAdvancedExperienceRelationshipsHeaderImage {
	this := AppClipAdvancedExperienceRelationshipsHeaderImage{}
	return &this
}

// NewAppClipAdvancedExperienceRelationshipsHeaderImageWithDefaults instantiates a new AppClipAdvancedExperienceRelationshipsHeaderImage object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppClipAdvancedExperienceRelationshipsHeaderImageWithDefaults() *AppClipAdvancedExperienceRelationshipsHeaderImage {
	this := AppClipAdvancedExperienceRelationshipsHeaderImage{}
	return &this
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *AppClipAdvancedExperienceRelationshipsHeaderImage) GetData() AppClipAdvancedExperienceRelationshipsHeaderImageData {
	if o == nil || IsNil(o.Data) {
		var ret AppClipAdvancedExperienceRelationshipsHeaderImageData
		return ret
	}
	return *o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppClipAdvancedExperienceRelationshipsHeaderImage) GetDataOk() (*AppClipAdvancedExperienceRelationshipsHeaderImageData, bool) {
	if o == nil || IsNil(o.Data) {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *AppClipAdvancedExperienceRelationshipsHeaderImage) HasData() bool {
	if o != nil && !IsNil(o.Data) {
		return true
	}

	return false
}

// SetData gets a reference to the given AppClipAdvancedExperienceRelationshipsHeaderImageData and assigns it to the Data field.
func (o *AppClipAdvancedExperienceRelationshipsHeaderImage) SetData(v AppClipAdvancedExperienceRelationshipsHeaderImageData) {
	o.Data = &v
}

func (o AppClipAdvancedExperienceRelationshipsHeaderImage) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppClipAdvancedExperienceRelationshipsHeaderImage) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Data) {
		toSerialize["data"] = o.Data
	}
	return toSerialize, nil
}

type NullableAppClipAdvancedExperienceRelationshipsHeaderImage struct {
	value *AppClipAdvancedExperienceRelationshipsHeaderImage
	isSet bool
}

func (v NullableAppClipAdvancedExperienceRelationshipsHeaderImage) Get() *AppClipAdvancedExperienceRelationshipsHeaderImage {
	return v.value
}

func (v *NullableAppClipAdvancedExperienceRelationshipsHeaderImage) Set(val *AppClipAdvancedExperienceRelationshipsHeaderImage) {
	v.value = val
	v.isSet = true
}

func (v NullableAppClipAdvancedExperienceRelationshipsHeaderImage) IsSet() bool {
	return v.isSet
}

func (v *NullableAppClipAdvancedExperienceRelationshipsHeaderImage) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppClipAdvancedExperienceRelationshipsHeaderImage(val *AppClipAdvancedExperienceRelationshipsHeaderImage) *NullableAppClipAdvancedExperienceRelationshipsHeaderImage {
	return &NullableAppClipAdvancedExperienceRelationshipsHeaderImage{value: val, isSet: true}
}

func (v NullableAppClipAdvancedExperienceRelationshipsHeaderImage) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppClipAdvancedExperienceRelationshipsHeaderImage) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


