/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect-client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AlternativeDistributionPackageCreateRequestDataRelationships type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AlternativeDistributionPackageCreateRequestDataRelationships{}

// AlternativeDistributionPackageCreateRequestDataRelationships struct for AlternativeDistributionPackageCreateRequestDataRelationships
type AlternativeDistributionPackageCreateRequestDataRelationships struct {
	AppStoreVersion AlternativeDistributionPackageCreateRequestDataRelationshipsAppStoreVersion `json:"appStoreVersion"`
}

type _AlternativeDistributionPackageCreateRequestDataRelationships AlternativeDistributionPackageCreateRequestDataRelationships

// NewAlternativeDistributionPackageCreateRequestDataRelationships instantiates a new AlternativeDistributionPackageCreateRequestDataRelationships object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAlternativeDistributionPackageCreateRequestDataRelationships(appStoreVersion AlternativeDistributionPackageCreateRequestDataRelationshipsAppStoreVersion) *AlternativeDistributionPackageCreateRequestDataRelationships {
	this := AlternativeDistributionPackageCreateRequestDataRelationships{}
	this.AppStoreVersion = appStoreVersion
	return &this
}

// NewAlternativeDistributionPackageCreateRequestDataRelationshipsWithDefaults instantiates a new AlternativeDistributionPackageCreateRequestDataRelationships object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAlternativeDistributionPackageCreateRequestDataRelationshipsWithDefaults() *AlternativeDistributionPackageCreateRequestDataRelationships {
	this := AlternativeDistributionPackageCreateRequestDataRelationships{}
	return &this
}

// GetAppStoreVersion returns the AppStoreVersion field value
func (o *AlternativeDistributionPackageCreateRequestDataRelationships) GetAppStoreVersion() AlternativeDistributionPackageCreateRequestDataRelationshipsAppStoreVersion {
	if o == nil {
		var ret AlternativeDistributionPackageCreateRequestDataRelationshipsAppStoreVersion
		return ret
	}

	return o.AppStoreVersion
}

// GetAppStoreVersionOk returns a tuple with the AppStoreVersion field value
// and a boolean to check if the value has been set.
func (o *AlternativeDistributionPackageCreateRequestDataRelationships) GetAppStoreVersionOk() (*AlternativeDistributionPackageCreateRequestDataRelationshipsAppStoreVersion, bool) {
	if o == nil {
		return nil, false
	}
	return &o.AppStoreVersion, true
}

// SetAppStoreVersion sets field value
func (o *AlternativeDistributionPackageCreateRequestDataRelationships) SetAppStoreVersion(v AlternativeDistributionPackageCreateRequestDataRelationshipsAppStoreVersion) {
	o.AppStoreVersion = v
}

func (o AlternativeDistributionPackageCreateRequestDataRelationships) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AlternativeDistributionPackageCreateRequestDataRelationships) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["appStoreVersion"] = o.AppStoreVersion
	return toSerialize, nil
}

func (o *AlternativeDistributionPackageCreateRequestDataRelationships) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"appStoreVersion",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAlternativeDistributionPackageCreateRequestDataRelationships := _AlternativeDistributionPackageCreateRequestDataRelationships{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAlternativeDistributionPackageCreateRequestDataRelationships)

	if err != nil {
		return err
	}

	*o = AlternativeDistributionPackageCreateRequestDataRelationships(varAlternativeDistributionPackageCreateRequestDataRelationships)

	return err
}

type NullableAlternativeDistributionPackageCreateRequestDataRelationships struct {
	value *AlternativeDistributionPackageCreateRequestDataRelationships
	isSet bool
}

func (v NullableAlternativeDistributionPackageCreateRequestDataRelationships) Get() *AlternativeDistributionPackageCreateRequestDataRelationships {
	return v.value
}

func (v *NullableAlternativeDistributionPackageCreateRequestDataRelationships) Set(val *AlternativeDistributionPackageCreateRequestDataRelationships) {
	v.value = val
	v.isSet = true
}

func (v NullableAlternativeDistributionPackageCreateRequestDataRelationships) IsSet() bool {
	return v.isSet
}

func (v *NullableAlternativeDistributionPackageCreateRequestDataRelationships) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAlternativeDistributionPackageCreateRequestDataRelationships(val *AlternativeDistributionPackageCreateRequestDataRelationships) *NullableAlternativeDistributionPackageCreateRequestDataRelationships {
	return &NullableAlternativeDistributionPackageCreateRequestDataRelationships{value: val, isSet: true}
}

func (v NullableAlternativeDistributionPackageCreateRequestDataRelationships) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAlternativeDistributionPackageCreateRequestDataRelationships) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


