/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnectclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the ReviewSubmissionCreateRequestData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &ReviewSubmissionCreateRequestData{}

// ReviewSubmissionCreateRequestData struct for ReviewSubmissionCreateRequestData
type ReviewSubmissionCreateRequestData struct {
	Type string `json:"type"`
	Attributes ReviewSubmissionCreateRequestDataAttributes `json:"attributes"`
	Relationships AnalyticsReportRequestCreateRequestDataRelationships `json:"relationships"`
}

type _ReviewSubmissionCreateRequestData ReviewSubmissionCreateRequestData

// NewReviewSubmissionCreateRequestData instantiates a new ReviewSubmissionCreateRequestData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewReviewSubmissionCreateRequestData(type_ string, attributes ReviewSubmissionCreateRequestDataAttributes, relationships AnalyticsReportRequestCreateRequestDataRelationships) *ReviewSubmissionCreateRequestData {
	this := ReviewSubmissionCreateRequestData{}
	this.Type = type_
	this.Attributes = attributes
	this.Relationships = relationships
	return &this
}

// NewReviewSubmissionCreateRequestDataWithDefaults instantiates a new ReviewSubmissionCreateRequestData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewReviewSubmissionCreateRequestDataWithDefaults() *ReviewSubmissionCreateRequestData {
	this := ReviewSubmissionCreateRequestData{}
	return &this
}

// GetType returns the Type field value
func (o *ReviewSubmissionCreateRequestData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *ReviewSubmissionCreateRequestData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *ReviewSubmissionCreateRequestData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *ReviewSubmissionCreateRequestData) GetAttributes() ReviewSubmissionCreateRequestDataAttributes {
	if o == nil {
		var ret ReviewSubmissionCreateRequestDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *ReviewSubmissionCreateRequestData) GetAttributesOk() (*ReviewSubmissionCreateRequestDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *ReviewSubmissionCreateRequestData) SetAttributes(v ReviewSubmissionCreateRequestDataAttributes) {
	o.Attributes = v
}

// GetRelationships returns the Relationships field value
func (o *ReviewSubmissionCreateRequestData) GetRelationships() AnalyticsReportRequestCreateRequestDataRelationships {
	if o == nil {
		var ret AnalyticsReportRequestCreateRequestDataRelationships
		return ret
	}

	return o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value
// and a boolean to check if the value has been set.
func (o *ReviewSubmissionCreateRequestData) GetRelationshipsOk() (*AnalyticsReportRequestCreateRequestDataRelationships, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Relationships, true
}

// SetRelationships sets field value
func (o *ReviewSubmissionCreateRequestData) SetRelationships(v AnalyticsReportRequestCreateRequestDataRelationships) {
	o.Relationships = v
}

func (o ReviewSubmissionCreateRequestData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o ReviewSubmissionCreateRequestData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	toSerialize["relationships"] = o.Relationships
	return toSerialize, nil
}

func (o *ReviewSubmissionCreateRequestData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
		"relationships",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varReviewSubmissionCreateRequestData := _ReviewSubmissionCreateRequestData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varReviewSubmissionCreateRequestData)

	if err != nil {
		return err
	}

	*o = ReviewSubmissionCreateRequestData(varReviewSubmissionCreateRequestData)

	return err
}

type NullableReviewSubmissionCreateRequestData struct {
	value *ReviewSubmissionCreateRequestData
	isSet bool
}

func (v NullableReviewSubmissionCreateRequestData) Get() *ReviewSubmissionCreateRequestData {
	return v.value
}

func (v *NullableReviewSubmissionCreateRequestData) Set(val *ReviewSubmissionCreateRequestData) {
	v.value = val
	v.isSet = true
}

func (v NullableReviewSubmissionCreateRequestData) IsSet() bool {
	return v.isSet
}

func (v *NullableReviewSubmissionCreateRequestData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableReviewSubmissionCreateRequestData(val *ReviewSubmissionCreateRequestData) *NullableReviewSubmissionCreateRequestData {
	return &NullableReviewSubmissionCreateRequestData{value: val, isSet: true}
}

func (v NullableReviewSubmissionCreateRequestData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableReviewSubmissionCreateRequestData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


