/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnectclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the BundleIdCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &BundleIdCreateRequest{}

// BundleIdCreateRequest struct for BundleIdCreateRequest
type BundleIdCreateRequest struct {
	Data BundleIdCreateRequestData `json:"data"`
}

type _BundleIdCreateRequest BundleIdCreateRequest

// NewBundleIdCreateRequest instantiates a new BundleIdCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewBundleIdCreateRequest(data BundleIdCreateRequestData) *BundleIdCreateRequest {
	this := BundleIdCreateRequest{}
	this.Data = data
	return &this
}

// NewBundleIdCreateRequestWithDefaults instantiates a new BundleIdCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewBundleIdCreateRequestWithDefaults() *BundleIdCreateRequest {
	this := BundleIdCreateRequest{}
	return &this
}

// GetData returns the Data field value
func (o *BundleIdCreateRequest) GetData() BundleIdCreateRequestData {
	if o == nil {
		var ret BundleIdCreateRequestData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *BundleIdCreateRequest) GetDataOk() (*BundleIdCreateRequestData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *BundleIdCreateRequest) SetData(v BundleIdCreateRequestData) {
	o.Data = v
}

func (o BundleIdCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o BundleIdCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *BundleIdCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varBundleIdCreateRequest := _BundleIdCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varBundleIdCreateRequest)

	if err != nil {
		return err
	}

	*o = BundleIdCreateRequest(varBundleIdCreateRequest)

	return err
}

type NullableBundleIdCreateRequest struct {
	value *BundleIdCreateRequest
	isSet bool
}

func (v NullableBundleIdCreateRequest) Get() *BundleIdCreateRequest {
	return v.value
}

func (v *NullableBundleIdCreateRequest) Set(val *BundleIdCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableBundleIdCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableBundleIdCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableBundleIdCreateRequest(val *BundleIdCreateRequest) *NullableBundleIdCreateRequest {
	return &NullableBundleIdCreateRequest{value: val, isSet: true}
}

func (v NullableBundleIdCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableBundleIdCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


