/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnectclient

import (
	"encoding/json"
)

// checks if the AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinks type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinks{}

// AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinks struct for AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinks
type AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinks struct {
	GroupBy *string `json:"groupBy,omitempty"`
	Related *string `json:"related,omitempty"`
}

// NewAppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinks instantiates a new AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinks object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinks() *AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinks {
	this := AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinks{}
	return &this
}

// NewAppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinksWithDefaults instantiates a new AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinks object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinksWithDefaults() *AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinks {
	this := AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinks{}
	return &this
}

// GetGroupBy returns the GroupBy field value if set, zero value otherwise.
func (o *AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinks) GetGroupBy() string {
	if o == nil || IsNil(o.GroupBy) {
		var ret string
		return ret
	}
	return *o.GroupBy
}

// GetGroupByOk returns a tuple with the GroupBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinks) GetGroupByOk() (*string, bool) {
	if o == nil || IsNil(o.GroupBy) {
		return nil, false
	}
	return o.GroupBy, true
}

// HasGroupBy returns a boolean if a field has been set.
func (o *AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinks) HasGroupBy() bool {
	if o != nil && !IsNil(o.GroupBy) {
		return true
	}

	return false
}

// SetGroupBy gets a reference to the given string and assigns it to the GroupBy field.
func (o *AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinks) SetGroupBy(v string) {
	o.GroupBy = &v
}

// GetRelated returns the Related field value if set, zero value otherwise.
func (o *AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinks) GetRelated() string {
	if o == nil || IsNil(o.Related) {
		var ret string
		return ret
	}
	return *o.Related
}

// GetRelatedOk returns a tuple with the Related field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinks) GetRelatedOk() (*string, bool) {
	if o == nil || IsNil(o.Related) {
		return nil, false
	}
	return o.Related, true
}

// HasRelated returns a boolean if a field has been set.
func (o *AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinks) HasRelated() bool {
	if o != nil && !IsNil(o.Related) {
		return true
	}

	return false
}

// SetRelated gets a reference to the given string and assigns it to the Related field.
func (o *AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinks) SetRelated(v string) {
	o.Related = &v
}

func (o AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinks) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinks) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.GroupBy) {
		toSerialize["groupBy"] = o.GroupBy
	}
	if !IsNil(o.Related) {
		toSerialize["related"] = o.Related
	}
	return toSerialize, nil
}

type NullableAppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinks struct {
	value *AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinks
	isSet bool
}

func (v NullableAppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinks) Get() *AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinks {
	return v.value
}

func (v *NullableAppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinks) Set(val *AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinks) {
	v.value = val
	v.isSet = true
}

func (v NullableAppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinks) IsSet() bool {
	return v.isSet
}

func (v *NullableAppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinks) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinks(val *AppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinks) *NullableAppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinks {
	return &NullableAppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinks{value: val, isSet: true}
}

func (v NullableAppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinks) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppsBetaTesterUsagesV1MetricResponseDataInnerDimensionsBetaTestersLinks) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


