/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnectclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the AppStoreVersionReleaseRequestCreateRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AppStoreVersionReleaseRequestCreateRequest{}

// AppStoreVersionReleaseRequestCreateRequest struct for AppStoreVersionReleaseRequestCreateRequest
type AppStoreVersionReleaseRequestCreateRequest struct {
	Data AppStoreVersionReleaseRequestCreateRequestData `json:"data"`
}

type _AppStoreVersionReleaseRequestCreateRequest AppStoreVersionReleaseRequestCreateRequest

// NewAppStoreVersionReleaseRequestCreateRequest instantiates a new AppStoreVersionReleaseRequestCreateRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAppStoreVersionReleaseRequestCreateRequest(data AppStoreVersionReleaseRequestCreateRequestData) *AppStoreVersionReleaseRequestCreateRequest {
	this := AppStoreVersionReleaseRequestCreateRequest{}
	this.Data = data
	return &this
}

// NewAppStoreVersionReleaseRequestCreateRequestWithDefaults instantiates a new AppStoreVersionReleaseRequestCreateRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAppStoreVersionReleaseRequestCreateRequestWithDefaults() *AppStoreVersionReleaseRequestCreateRequest {
	this := AppStoreVersionReleaseRequestCreateRequest{}
	return &this
}

// GetData returns the Data field value
func (o *AppStoreVersionReleaseRequestCreateRequest) GetData() AppStoreVersionReleaseRequestCreateRequestData {
	if o == nil {
		var ret AppStoreVersionReleaseRequestCreateRequestData
		return ret
	}

	return o.Data
}

// GetDataOk returns a tuple with the Data field value
// and a boolean to check if the value has been set.
func (o *AppStoreVersionReleaseRequestCreateRequest) GetDataOk() (*AppStoreVersionReleaseRequestCreateRequestData, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Data, true
}

// SetData sets field value
func (o *AppStoreVersionReleaseRequestCreateRequest) SetData(v AppStoreVersionReleaseRequestCreateRequestData) {
	o.Data = v
}

func (o AppStoreVersionReleaseRequestCreateRequest) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AppStoreVersionReleaseRequestCreateRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["data"] = o.Data
	return toSerialize, nil
}

func (o *AppStoreVersionReleaseRequestCreateRequest) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"data",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varAppStoreVersionReleaseRequestCreateRequest := _AppStoreVersionReleaseRequestCreateRequest{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varAppStoreVersionReleaseRequestCreateRequest)

	if err != nil {
		return err
	}

	*o = AppStoreVersionReleaseRequestCreateRequest(varAppStoreVersionReleaseRequestCreateRequest)

	return err
}

type NullableAppStoreVersionReleaseRequestCreateRequest struct {
	value *AppStoreVersionReleaseRequestCreateRequest
	isSet bool
}

func (v NullableAppStoreVersionReleaseRequestCreateRequest) Get() *AppStoreVersionReleaseRequestCreateRequest {
	return v.value
}

func (v *NullableAppStoreVersionReleaseRequestCreateRequest) Set(val *AppStoreVersionReleaseRequestCreateRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAppStoreVersionReleaseRequestCreateRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAppStoreVersionReleaseRequestCreateRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAppStoreVersionReleaseRequestCreateRequest(val *AppStoreVersionReleaseRequestCreateRequest) *NullableAppStoreVersionReleaseRequestCreateRequest {
	return &NullableAppStoreVersionReleaseRequestCreateRequest{value: val, isSet: true}
}

func (v NullableAppStoreVersionReleaseRequestCreateRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAppStoreVersionReleaseRequestCreateRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


