/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnectclient

import (
	"encoding/json"
)

// checks if the MarketplaceWebhookUpdateRequestDataAttributes type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &MarketplaceWebhookUpdateRequestDataAttributes{}

// MarketplaceWebhookUpdateRequestDataAttributes struct for MarketplaceWebhookUpdateRequestDataAttributes
type MarketplaceWebhookUpdateRequestDataAttributes struct {
	EndpointUrl *string `json:"endpointUrl,omitempty"`
	Secret *string `json:"secret,omitempty"`
}

// NewMarketplaceWebhookUpdateRequestDataAttributes instantiates a new MarketplaceWebhookUpdateRequestDataAttributes object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewMarketplaceWebhookUpdateRequestDataAttributes() *MarketplaceWebhookUpdateRequestDataAttributes {
	this := MarketplaceWebhookUpdateRequestDataAttributes{}
	return &this
}

// NewMarketplaceWebhookUpdateRequestDataAttributesWithDefaults instantiates a new MarketplaceWebhookUpdateRequestDataAttributes object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewMarketplaceWebhookUpdateRequestDataAttributesWithDefaults() *MarketplaceWebhookUpdateRequestDataAttributes {
	this := MarketplaceWebhookUpdateRequestDataAttributes{}
	return &this
}

// GetEndpointUrl returns the EndpointUrl field value if set, zero value otherwise.
func (o *MarketplaceWebhookUpdateRequestDataAttributes) GetEndpointUrl() string {
	if o == nil || IsNil(o.EndpointUrl) {
		var ret string
		return ret
	}
	return *o.EndpointUrl
}

// GetEndpointUrlOk returns a tuple with the EndpointUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarketplaceWebhookUpdateRequestDataAttributes) GetEndpointUrlOk() (*string, bool) {
	if o == nil || IsNil(o.EndpointUrl) {
		return nil, false
	}
	return o.EndpointUrl, true
}

// HasEndpointUrl returns a boolean if a field has been set.
func (o *MarketplaceWebhookUpdateRequestDataAttributes) HasEndpointUrl() bool {
	if o != nil && !IsNil(o.EndpointUrl) {
		return true
	}

	return false
}

// SetEndpointUrl gets a reference to the given string and assigns it to the EndpointUrl field.
func (o *MarketplaceWebhookUpdateRequestDataAttributes) SetEndpointUrl(v string) {
	o.EndpointUrl = &v
}

// GetSecret returns the Secret field value if set, zero value otherwise.
func (o *MarketplaceWebhookUpdateRequestDataAttributes) GetSecret() string {
	if o == nil || IsNil(o.Secret) {
		var ret string
		return ret
	}
	return *o.Secret
}

// GetSecretOk returns a tuple with the Secret field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *MarketplaceWebhookUpdateRequestDataAttributes) GetSecretOk() (*string, bool) {
	if o == nil || IsNil(o.Secret) {
		return nil, false
	}
	return o.Secret, true
}

// HasSecret returns a boolean if a field has been set.
func (o *MarketplaceWebhookUpdateRequestDataAttributes) HasSecret() bool {
	if o != nil && !IsNil(o.Secret) {
		return true
	}

	return false
}

// SetSecret gets a reference to the given string and assigns it to the Secret field.
func (o *MarketplaceWebhookUpdateRequestDataAttributes) SetSecret(v string) {
	o.Secret = &v
}

func (o MarketplaceWebhookUpdateRequestDataAttributes) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o MarketplaceWebhookUpdateRequestDataAttributes) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.EndpointUrl) {
		toSerialize["endpointUrl"] = o.EndpointUrl
	}
	if !IsNil(o.Secret) {
		toSerialize["secret"] = o.Secret
	}
	return toSerialize, nil
}

type NullableMarketplaceWebhookUpdateRequestDataAttributes struct {
	value *MarketplaceWebhookUpdateRequestDataAttributes
	isSet bool
}

func (v NullableMarketplaceWebhookUpdateRequestDataAttributes) Get() *MarketplaceWebhookUpdateRequestDataAttributes {
	return v.value
}

func (v *NullableMarketplaceWebhookUpdateRequestDataAttributes) Set(val *MarketplaceWebhookUpdateRequestDataAttributes) {
	v.value = val
	v.isSet = true
}

func (v NullableMarketplaceWebhookUpdateRequestDataAttributes) IsSet() bool {
	return v.isSet
}

func (v *NullableMarketplaceWebhookUpdateRequestDataAttributes) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableMarketplaceWebhookUpdateRequestDataAttributes(val *MarketplaceWebhookUpdateRequestDataAttributes) *NullableMarketplaceWebhookUpdateRequestDataAttributes {
	return &NullableMarketplaceWebhookUpdateRequestDataAttributes{value: val, isSet: true}
}

func (v NullableMarketplaceWebhookUpdateRequestDataAttributes) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableMarketplaceWebhookUpdateRequestDataAttributes) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


