/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnect-client

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GameCenterMatchmakingRuleUpdateRequestData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GameCenterMatchmakingRuleUpdateRequestData{}

// GameCenterMatchmakingRuleUpdateRequestData struct for GameCenterMatchmakingRuleUpdateRequestData
type GameCenterMatchmakingRuleUpdateRequestData struct {
	Type string `json:"type"`
	Id string `json:"id"`
	Attributes *GameCenterMatchmakingRuleUpdateRequestDataAttributes `json:"attributes,omitempty"`
}

type _GameCenterMatchmakingRuleUpdateRequestData GameCenterMatchmakingRuleUpdateRequestData

// NewGameCenterMatchmakingRuleUpdateRequestData instantiates a new GameCenterMatchmakingRuleUpdateRequestData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGameCenterMatchmakingRuleUpdateRequestData(type_ string, id string) *GameCenterMatchmakingRuleUpdateRequestData {
	this := GameCenterMatchmakingRuleUpdateRequestData{}
	this.Type = type_
	this.Id = id
	return &this
}

// NewGameCenterMatchmakingRuleUpdateRequestDataWithDefaults instantiates a new GameCenterMatchmakingRuleUpdateRequestData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGameCenterMatchmakingRuleUpdateRequestDataWithDefaults() *GameCenterMatchmakingRuleUpdateRequestData {
	this := GameCenterMatchmakingRuleUpdateRequestData{}
	return &this
}

// GetType returns the Type field value
func (o *GameCenterMatchmakingRuleUpdateRequestData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GameCenterMatchmakingRuleUpdateRequestData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GameCenterMatchmakingRuleUpdateRequestData) SetType(v string) {
	o.Type = v
}

// GetId returns the Id field value
func (o *GameCenterMatchmakingRuleUpdateRequestData) GetId() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
func (o *GameCenterMatchmakingRuleUpdateRequestData) GetIdOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *GameCenterMatchmakingRuleUpdateRequestData) SetId(v string) {
	o.Id = v
}

// GetAttributes returns the Attributes field value if set, zero value otherwise.
func (o *GameCenterMatchmakingRuleUpdateRequestData) GetAttributes() GameCenterMatchmakingRuleUpdateRequestDataAttributes {
	if o == nil || IsNil(o.Attributes) {
		var ret GameCenterMatchmakingRuleUpdateRequestDataAttributes
		return ret
	}
	return *o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GameCenterMatchmakingRuleUpdateRequestData) GetAttributesOk() (*GameCenterMatchmakingRuleUpdateRequestDataAttributes, bool) {
	if o == nil || IsNil(o.Attributes) {
		return nil, false
	}
	return o.Attributes, true
}

// HasAttributes returns a boolean if a field has been set.
func (o *GameCenterMatchmakingRuleUpdateRequestData) HasAttributes() bool {
	if o != nil && !IsNil(o.Attributes) {
		return true
	}

	return false
}

// SetAttributes gets a reference to the given GameCenterMatchmakingRuleUpdateRequestDataAttributes and assigns it to the Attributes field.
func (o *GameCenterMatchmakingRuleUpdateRequestData) SetAttributes(v GameCenterMatchmakingRuleUpdateRequestDataAttributes) {
	o.Attributes = &v
}

func (o GameCenterMatchmakingRuleUpdateRequestData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GameCenterMatchmakingRuleUpdateRequestData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["id"] = o.Id
	if !IsNil(o.Attributes) {
		toSerialize["attributes"] = o.Attributes
	}
	return toSerialize, nil
}

func (o *GameCenterMatchmakingRuleUpdateRequestData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"id",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGameCenterMatchmakingRuleUpdateRequestData := _GameCenterMatchmakingRuleUpdateRequestData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGameCenterMatchmakingRuleUpdateRequestData)

	if err != nil {
		return err
	}

	*o = GameCenterMatchmakingRuleUpdateRequestData(varGameCenterMatchmakingRuleUpdateRequestData)

	return err
}

type NullableGameCenterMatchmakingRuleUpdateRequestData struct {
	value *GameCenterMatchmakingRuleUpdateRequestData
	isSet bool
}

func (v NullableGameCenterMatchmakingRuleUpdateRequestData) Get() *GameCenterMatchmakingRuleUpdateRequestData {
	return v.value
}

func (v *NullableGameCenterMatchmakingRuleUpdateRequestData) Set(val *GameCenterMatchmakingRuleUpdateRequestData) {
	v.value = val
	v.isSet = true
}

func (v NullableGameCenterMatchmakingRuleUpdateRequestData) IsSet() bool {
	return v.isSet
}

func (v *NullableGameCenterMatchmakingRuleUpdateRequestData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGameCenterMatchmakingRuleUpdateRequestData(val *GameCenterMatchmakingRuleUpdateRequestData) *NullableGameCenterMatchmakingRuleUpdateRequestData {
	return &NullableGameCenterMatchmakingRuleUpdateRequestData{value: val, isSet: true}
}

func (v NullableGameCenterMatchmakingRuleUpdateRequestData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGameCenterMatchmakingRuleUpdateRequestData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


