/*
App Store Connect API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 3.6.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package appstoreconnectclient

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the GameCenterLeaderboardSetImageCreateRequestData type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GameCenterLeaderboardSetImageCreateRequestData{}

// GameCenterLeaderboardSetImageCreateRequestData struct for GameCenterLeaderboardSetImageCreateRequestData
type GameCenterLeaderboardSetImageCreateRequestData struct {
	Type string `json:"type"`
	Attributes AppClipAdvancedExperienceImageCreateRequestDataAttributes `json:"attributes"`
	Relationships GameCenterLeaderboardSetImageCreateRequestDataRelationships `json:"relationships"`
}

type _GameCenterLeaderboardSetImageCreateRequestData GameCenterLeaderboardSetImageCreateRequestData

// NewGameCenterLeaderboardSetImageCreateRequestData instantiates a new GameCenterLeaderboardSetImageCreateRequestData object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGameCenterLeaderboardSetImageCreateRequestData(type_ string, attributes AppClipAdvancedExperienceImageCreateRequestDataAttributes, relationships GameCenterLeaderboardSetImageCreateRequestDataRelationships) *GameCenterLeaderboardSetImageCreateRequestData {
	this := GameCenterLeaderboardSetImageCreateRequestData{}
	this.Type = type_
	this.Attributes = attributes
	this.Relationships = relationships
	return &this
}

// NewGameCenterLeaderboardSetImageCreateRequestDataWithDefaults instantiates a new GameCenterLeaderboardSetImageCreateRequestData object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGameCenterLeaderboardSetImageCreateRequestDataWithDefaults() *GameCenterLeaderboardSetImageCreateRequestData {
	this := GameCenterLeaderboardSetImageCreateRequestData{}
	return &this
}

// GetType returns the Type field value
func (o *GameCenterLeaderboardSetImageCreateRequestData) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *GameCenterLeaderboardSetImageCreateRequestData) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *GameCenterLeaderboardSetImageCreateRequestData) SetType(v string) {
	o.Type = v
}

// GetAttributes returns the Attributes field value
func (o *GameCenterLeaderboardSetImageCreateRequestData) GetAttributes() AppClipAdvancedExperienceImageCreateRequestDataAttributes {
	if o == nil {
		var ret AppClipAdvancedExperienceImageCreateRequestDataAttributes
		return ret
	}

	return o.Attributes
}

// GetAttributesOk returns a tuple with the Attributes field value
// and a boolean to check if the value has been set.
func (o *GameCenterLeaderboardSetImageCreateRequestData) GetAttributesOk() (*AppClipAdvancedExperienceImageCreateRequestDataAttributes, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Attributes, true
}

// SetAttributes sets field value
func (o *GameCenterLeaderboardSetImageCreateRequestData) SetAttributes(v AppClipAdvancedExperienceImageCreateRequestDataAttributes) {
	o.Attributes = v
}

// GetRelationships returns the Relationships field value
func (o *GameCenterLeaderboardSetImageCreateRequestData) GetRelationships() GameCenterLeaderboardSetImageCreateRequestDataRelationships {
	if o == nil {
		var ret GameCenterLeaderboardSetImageCreateRequestDataRelationships
		return ret
	}

	return o.Relationships
}

// GetRelationshipsOk returns a tuple with the Relationships field value
// and a boolean to check if the value has been set.
func (o *GameCenterLeaderboardSetImageCreateRequestData) GetRelationshipsOk() (*GameCenterLeaderboardSetImageCreateRequestDataRelationships, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Relationships, true
}

// SetRelationships sets field value
func (o *GameCenterLeaderboardSetImageCreateRequestData) SetRelationships(v GameCenterLeaderboardSetImageCreateRequestDataRelationships) {
	o.Relationships = v
}

func (o GameCenterLeaderboardSetImageCreateRequestData) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GameCenterLeaderboardSetImageCreateRequestData) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["attributes"] = o.Attributes
	toSerialize["relationships"] = o.Relationships
	return toSerialize, nil
}

func (o *GameCenterLeaderboardSetImageCreateRequestData) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"attributes",
		"relationships",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varGameCenterLeaderboardSetImageCreateRequestData := _GameCenterLeaderboardSetImageCreateRequestData{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varGameCenterLeaderboardSetImageCreateRequestData)

	if err != nil {
		return err
	}

	*o = GameCenterLeaderboardSetImageCreateRequestData(varGameCenterLeaderboardSetImageCreateRequestData)

	return err
}

type NullableGameCenterLeaderboardSetImageCreateRequestData struct {
	value *GameCenterLeaderboardSetImageCreateRequestData
	isSet bool
}

func (v NullableGameCenterLeaderboardSetImageCreateRequestData) Get() *GameCenterLeaderboardSetImageCreateRequestData {
	return v.value
}

func (v *NullableGameCenterLeaderboardSetImageCreateRequestData) Set(val *GameCenterLeaderboardSetImageCreateRequestData) {
	v.value = val
	v.isSet = true
}

func (v NullableGameCenterLeaderboardSetImageCreateRequestData) IsSet() bool {
	return v.isSet
}

func (v *NullableGameCenterLeaderboardSetImageCreateRequestData) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGameCenterLeaderboardSetImageCreateRequestData(val *GameCenterLeaderboardSetImageCreateRequestData) *NullableGameCenterLeaderboardSetImageCreateRequestData {
	return &NullableGameCenterLeaderboardSetImageCreateRequestData{value: val, isSet: true}
}

func (v NullableGameCenterLeaderboardSetImageCreateRequestData) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGameCenterLeaderboardSetImageCreateRequestData) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


